auto: true
markdown: kramdown
highlighter: rouge
permalink: /article/:title
paginate: 5
exclude: [excludethis]

# variables
title: NNDDCC
tagline: Personal Website of Endy Tjahjono
url: http://www.endycahyono.com
owner: Endy Tjahjono
