auto: true
markdown: redcarpet
pygments: true
permalink: /blog/:title
paginate: 5
exclude: excludethis

# variables
title: NNDDCC
tagline: Personal Web Pages of Endy Tjahjono
url: http://endycahyono.com
