auto: true
markdown: redcarpet
pygments: true
permalink: /article/:title
paginate: 5
exclude: excludethis

# variables
title: NNDDCC
tagline: Personal Website of Endy Tjahjono
url: http://endycahyono.com
owner: Endy Tjahjono
